"""Add career_memory schema

Revision ID: 56b4ce2a1714
Revises: c5583323fc6a
Create Date: 2026-07-05 15:40:57.553658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56b4ce2a1714"
down_revision: Union[str, Sequence[str], None] = "c5583323fc6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_memory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "project",
                "skill",
                "achievement",
                "education",
                "employment_history",
                name="memoryentitytype",
            ),
            nullable=False,
        ),
        sa.Column("fact_key", sa.String(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_career_memory_entity_type"),
        "career_memory",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_memory_user_id"), "career_memory", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_career_memory_user_id"), table_name="career_memory")
    op.drop_index(op.f("ix_career_memory_entity_type"), table_name="career_memory")
    op.drop_table("career_memory")
    # ### end Alembic commands ###
