"""apply_audit_remediation

Revision ID: 6413a88998d7
Revises: 38413d1b77aa
Create Date: 2026-07-08 17:15:18.025111

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6413a88998d7"
down_revision: str | Sequence[str] | None = "38413d1b77aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_job_matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_id", name="uq_user_job_matches_user_job"),
    )
    # Ignored checkpoint tables
    op.drop_index(
        op.f("idx_jobs_skills_bm25"),
        table_name="jobs",
        postgresql_with={"text_config": "english"},
        postgresql_using="bm25",
    )
    op.create_index(
        "idx_jobs_countries_gin",
        "jobs",
        ["countries"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_jobs_locations_gin",
        "jobs",
        ["locations"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_jobs_required_skills_gin",
        "jobs",
        ["required_skills"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_jobs_seniority_gin",
        "jobs",
        ["seniority"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("jobs", "skills_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "skills_text",
            sa.VARCHAR(),
            sa.Computed(
                "immutable_array_to_string((required_skills)::text[], ' '::text)",
                persisted=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("idx_jobs_seniority_gin", table_name="jobs", postgresql_using="gin")
    op.drop_index(
        "idx_jobs_required_skills_gin", table_name="jobs", postgresql_using="gin"
    )
    op.drop_index("idx_jobs_locations_gin", table_name="jobs", postgresql_using="gin")
    op.drop_index("idx_jobs_countries_gin", table_name="jobs", postgresql_using="gin")
    op.create_index(
        op.f("idx_jobs_skills_bm25"),
        "jobs",
        ["skills_text"],
        unique=False,
        postgresql_with={"text_config": "english"},
        postgresql_using="bm25",
    )
    # Ignored checkpoint tables
    op.drop_table("user_job_matches")
    # ### end Alembic commands ###
