"""add_application_draft_fields

Revision ID: 85e4caeac6d9
Revises: 6c509e73e48d
Create Date: 2026-07-06 19:51:07.398136

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85e4caeac6d9"
down_revision: str | Sequence[str] | None = "6c509e73e48d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checkpoint_migrations")
    op.drop_index(op.f("checkpoints_thread_id_idx"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_index(
        op.f("checkpoint_writes_thread_id_idx"), table_name="checkpoint_writes"
    )
    op.drop_table("checkpoint_writes")
    op.drop_index(op.f("checkpoint_blobs_thread_id_idx"), table_name="checkpoint_blobs")
    op.drop_table("checkpoint_blobs")
    op.add_column("applications", sa.Column("resume_draft", sa.Text(), nullable=True))
    op.add_column(
        "applications", sa.Column("cover_letter_draft", sa.Text(), nullable=True)
    )
    op.add_column(
        "applications",
        sa.Column("revision_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("applications", sa.Column("critique", sa.Text(), nullable=True))
    op.add_column("applications", sa.Column("fitness_score", sa.Float(), nullable=True))
    op.drop_index(
        op.f("idx_jobs_skills_bm25"),
        table_name="jobs",
        postgresql_with={"text_config": "english"},
        postgresql_using="bm25",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_jobs_skills_bm25"),
        "jobs",
        ["skills_text"],
        unique=False,
        postgresql_with={"text_config": "english"},
        postgresql_using="bm25",
    )
    op.drop_column("applications", "fitness_score")
    op.drop_column("applications", "critique")
    op.drop_column("applications", "revision_count")
    op.drop_column("applications", "cover_letter_draft")
    op.drop_column("applications", "resume_draft")
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "channel",
            "version",
            name=op.f("checkpoint_blobs_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_blobs_thread_id_idx"),
        "checkpoint_blobs",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("idx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "task_path",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name=op.f("checkpoint_writes_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_writes_thread_id_idx"),
        "checkpoint_writes",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "parent_checkpoint_id", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name=op.f("checkpoints_pkey")
        ),
    )
    op.create_index(
        op.f("checkpoints_thread_id_idx"), "checkpoints", ["thread_id"], unique=False
    )
    op.create_table(
        "checkpoint_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name=op.f("checkpoint_migrations_pkey")),
    )
    # ### end Alembic commands ###
